INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H
.DATA
  ;N DW "MY NAME IS SNIGDHA SAHA"
.CODE 
  MAIN PROC
     MOV CX,10
     
     START:
     PRINTN "AS"
     LOOP START
     
     MOV AH,4CH
     INT 21H
   MAIN ENDP
END MAIN
        